package view;

import controller.SeatController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controller.PersonController;
import model.Person;

/**
 *
 * @author Devil
 */
public class FrmLogOutClient extends javax.swing.JFrame {

    private SeatController seatController;
    DefaultTableModel tableClients2;
    String[] columns = {"Cedula", "Nombres", "Apellidos", "Numero", "Direccion", "Email"};
    PersonController personController;
    Object data[][];

    /**
     * Creates new form FrmLogOutClient
     */
    public FrmLogOutClient() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);
        panelAddClients.setVisible(false);
        panelAddSeats.setVisible(false);
        personController = new PersonController();
        seatController = new SeatController();
        btnGetBackHome4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showTable();
    }

    public void showTable() {
		
        data = personController.showAllPerson();
        if(data == null){
            System.out.println("vacio");
        }
        tableClients2 = new DefaultTableModel(data, columns);
        tableClients.setModel(tableClients2);
        tableClients.validate();
        tableClients.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGetBackHome4 = new javax.swing.JButton();
        panelAddClients = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtLogOutClientPhone = new javax.swing.JTextField();
        btnRegisterClient = new javax.swing.JButton();
        txtLogOutClientAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLogOutClientEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLogOutClientCC = new javax.swing.JTextField();
        txtLogOutClientName = new javax.swing.JTextField();
        txtLogOutClientLastName = new javax.swing.JTextField();
        panelAddSeats = new javax.swing.JPanel();
        btnAddAllSeats = new javax.swing.JButton();
        btnAddSeats = new javax.swing.JButton();
        btnAddClients = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClients = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGetBackHome4.setBackground(new java.awt.Color(255, 255, 255));
        btnGetBackHome4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconoBotonVolver.png"))); // NOI18N
        btnGetBackHome4.setText("VOLVER");
        btnGetBackHome4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGetBackHome4.setContentAreaFilled(false);
        btnGetBackHome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetBackHome4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Ingrese los datos del cliente");

        btnRegisterClient.setText("Registrar");
        btnRegisterClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterClientActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Datos cliente");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconoPersona.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        txtLogOutClientCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLogOutClientCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAddClientsLayout = new javax.swing.GroupLayout(panelAddClients);
        panelAddClients.setLayout(panelAddClientsLayout);
        panelAddClientsLayout.setHorizontalGroup(
            panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddClientsLayout.createSequentialGroup()
                .addGroup(panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddClientsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAddClientsLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLogOutClientCC)
                                    .addComponent(txtLogOutClientName)
                                    .addComponent(txtLogOutClientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLogOutClientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLogOutClientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLogOutClientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelAddClientsLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5)))
                    .addGroup(panelAddClientsLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnRegisterClient)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAddClientsLayout.setVerticalGroup(
            panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddClientsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addComponent(txtLogOutClientCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtLogOutClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtLogOutClientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtLogOutClientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtLogOutClientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtLogOutClientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnRegisterClient)
                .addGap(48, 48, 48))
        );

        btnAddAllSeats.setText("Agregar Asientos");
        btnAddAllSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAllSeatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAddSeatsLayout = new javax.swing.GroupLayout(panelAddSeats);
        panelAddSeats.setLayout(panelAddSeatsLayout);
        panelAddSeatsLayout.setHorizontalGroup(
            panelAddSeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddSeatsLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(btnAddAllSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        panelAddSeatsLayout.setVerticalGroup(
            panelAddSeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddSeatsLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(btnAddAllSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        btnAddSeats.setText("Agregar Asientos");
        btnAddSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSeatsActionPerformed(evt);
            }
        });

        btnAddClients.setText("Agregar Clientes");
        btnAddClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClientsActionPerformed(evt);
            }
        });

        tableClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableClients);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Clientes existentes en la base de datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnGetBackHome4)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAddSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnAddSeats)))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAddClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnAddClients)))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1)))
                .addContainerGap(411, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGetBackHome4)
                .addGap(297, 297, 297))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAddSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelAddClients, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSeats)
                    .addComponent(btnAddClients))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLogOutClientCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLogOutClientCCActionPerformed
        if (Validator.isEmpty(txtLogOutClientCC.getText()) && Validator.isEmpty(txtLogOutClientName.getText())
                && Validator.isEmpty(txtLogOutClientLastName.getText()) && Validator.isEmpty(txtLogOutClientPhone.getText())
                && Validator.isEmpty(txtLogOutClientAddress.getText()) && Validator.isEmpty(txtLogOutClientEmail.getText())) {
            JOptionPane.showMessageDialog(this, "Llena todos los campos para registrar el cliente");
            return;
        }
    }//GEN-LAST:event_txtLogOutClientCCActionPerformed

    private void btnGetBackHome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetBackHome4ActionPerformed
        FrmCinemaManagement getBackHome = new FrmCinemaManagement();
        getBackHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGetBackHome4ActionPerformed

    private void btnRegisterClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterClientActionPerformed
        if (Validator.isEmpty(txtLogOutClientCC.getText()) && Validator.isEmpty(txtLogOutClientName.getText())
                && Validator.isEmpty(txtLogOutClientLastName.getText()) && Validator.isEmpty(txtLogOutClientPhone.getText())
                && Validator.isEmpty(txtLogOutClientAddress.getText()) && Validator.isEmpty(txtLogOutClientEmail.getText())) {
            JOptionPane.showMessageDialog(this, "Llena todos los campos para registrar el cliente");
            return;
        }
        boolean confirm = personController.insertPerson(new Person(txtLogOutClientCC.getText(), txtLogOutClientName.getText(),
                txtLogOutClientLastName.getText(), txtLogOutClientPhone.getText(), txtLogOutClientAddress.getText(), txtLogOutClientEmail.getText()));
        if(confirm){
            System.out.println("se agrego");
        }else{
            System.out.println("No se agrego");
        }
        showTable();
    }//GEN-LAST:event_btnRegisterClientActionPerformed

    private void btnAddSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSeatsActionPerformed
        panelAddSeats.setVisible(true);
        panelAddClients.setVisible(false);
    }//GEN-LAST:event_btnAddSeatsActionPerformed

    private void btnAddClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClientsActionPerformed
        panelAddSeats.setVisible(false);
        panelAddClients.setVisible(true);
    }//GEN-LAST:event_btnAddClientsActionPerformed

    private void btnAddAllSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAllSeatsActionPerformed

        String[] seats = {"A1", "B1", "C1", "D1", "E1", "F1", "G1",
            "A2", "B2", "C2", "D2", "E2", "F2", "G2",
            "A3", "B3", "C3", "D3", "E3", "F3", "G3",
            "A4", "B4", "C4", "D4", "E4", "F4", "G4",
            "A5", "B5", "C5", "D5", "E5", "F5", "G5",
            "A6", "B6", "C6", "D6", "E6", "F6", "G6"
        };

        boolean seatsAdded = seatController.insertAllSeats(seats);

        if (seatsAdded) {
            JOptionPane.showMessageDialog(this, "asientos agregados correctamente a la base de datos");
        } else {
            JOptionPane.showMessageDialog(this, "asientos no agregados");
        }
    }//GEN-LAST:event_btnAddAllSeatsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogOutClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogOutClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogOutClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogOutClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogOutClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAllSeats;
    private javax.swing.JButton btnAddClients;
    private javax.swing.JButton btnAddSeats;
    private javax.swing.JButton btnGetBackHome4;
    private javax.swing.JButton btnRegisterClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelAddClients;
    private javax.swing.JPanel panelAddSeats;
    private javax.swing.JTable tableClients;
    private javax.swing.JTextField txtLogOutClientAddress;
    private javax.swing.JTextField txtLogOutClientCC;
    private javax.swing.JTextField txtLogOutClientEmail;
    private javax.swing.JTextField txtLogOutClientLastName;
    private javax.swing.JTextField txtLogOutClientName;
    private javax.swing.JTextField txtLogOutClientPhone;
    // End of variables declaration//GEN-END:variables
}
