package view;

import controller.SeatController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controller.PersonController;
import model.Person;

/**
 *
 * @author Devil
 */
public class FrmLogOutClient extends javax.swing.JFrame {

    private SeatController seatController;
    DefaultTableModel tableClients2;
    String[] columns = {"Cedula", "Nombres", "Apellidos", "Numero", "Direccion", "Email"};
    PersonController personController;
    Object data[][];

    /**
     * Creates new form FrmLogOutClient
     */
    public FrmLogOutClient() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);
        panelAddClients.setVisible(false);
        panelAddSeats.setVisible(false);
        personController = new PersonController();
        seatController = new SeatController();
        btnAddSeats.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddClients.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemoveClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showTable();
    }

    public void showTable() {
		
        data = personController.showAllPerson();
        if(data == null){
            System.out.println("vacio");
        }
        tableClients2 = new DefaultTableModel(data, columns);
        tableClients.setModel(tableClients2);
        tableClients.validate();
        tableClients.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAddClients = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtLogOutClientPhone = new javax.swing.JTextField();
        btnRegisterClient = new javax.swing.JButton();
        txtLogOutClientAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLogOutClientEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLogOutClientCC = new javax.swing.JTextField();
        txtLogOutClientName = new javax.swing.JTextField();
        txtLogOutClientLastName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panelAddSeats = new javax.swing.JPanel();
        btnAddAllSeats = new javax.swing.JButton();
        btnAddSeats = new javax.swing.JButton();
        btnAddClients = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClients = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGetBackHome5 = new javax.swing.JButton();
        btnUpdateClient = new javax.swing.JButton();
        btnRemoveClient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("Ingrese los datos del cliente");

        btnRegisterClient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegisterClient.setText("Registrar");
        btnRegisterClient.setContentAreaFilled(false);
        btnRegisterClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterClientActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setText("Datos cliente");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconoPersona.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        txtLogOutClientCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLogOutClientCCActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("CC");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Nombre");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Apellido");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Telefono");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Direccion");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Email");

        javax.swing.GroupLayout panelAddClientsLayout = new javax.swing.GroupLayout(panelAddClients);
        panelAddClients.setLayout(panelAddClientsLayout);
        panelAddClientsLayout.setHorizontalGroup(
            panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddClientsLayout.createSequentialGroup()
                .addGroup(panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddClientsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAddClientsLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5)
                            .addGroup(panelAddClientsLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(btnRegisterClient))))
                    .addGroup(panelAddClientsLayout.createSequentialGroup()
                        .addGroup(panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAddClientsLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddClientsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLogOutClientCC)
                            .addComponent(txtLogOutClientName)
                            .addComponent(txtLogOutClientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLogOutClientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLogOutClientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLogOutClientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelAddClientsLayout.setVerticalGroup(
            panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddClientsLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addGroup(panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogOutClientCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogOutClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogOutClientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogOutClientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogOutClientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(panelAddClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogOutClientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(43, 43, 43)
                .addComponent(btnRegisterClient)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        getContentPane().add(panelAddClients);
        panelAddClients.setBounds(546, 190, 300, 515);

        btnAddAllSeats.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAddAllSeats.setText("Agregar Asientos");
        btnAddAllSeats.setContentAreaFilled(false);
        btnAddAllSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAllSeatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAddSeatsLayout = new javax.swing.GroupLayout(panelAddSeats);
        panelAddSeats.setLayout(panelAddSeatsLayout);
        panelAddSeatsLayout.setHorizontalGroup(
            panelAddSeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddSeatsLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(btnAddAllSeats)
                .addGap(43, 43, 43))
        );
        panelAddSeatsLayout.setVerticalGroup(
            panelAddSeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddSeatsLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btnAddAllSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        getContentPane().add(panelAddSeats);
        panelAddSeats.setBounds(210, 270, 270, 375);

        btnAddSeats.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddSeats.setText("Agregar Asientos");
        btnAddSeats.setContentAreaFilled(false);
        btnAddSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSeatsActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddSeats);
        btnAddSeats.setBounds(270, 710, 150, 23);

        btnAddClients.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAddClients.setText("Agregar Clientes");
        btnAddClients.setContentAreaFilled(false);
        btnAddClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClientsActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddClients);
        btnAddClients.setBounds(640, 740, 172, 23);

        tableClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableClients);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(910, 310, 650, 430);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel1.setText("Clientes existentes en la base de datos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1030, 260, 410, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CortinasCine.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(136, -1, 1160, 250);

        btnGetBackHome5.setBackground(new java.awt.Color(255, 255, 255));
        btnGetBackHome5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IconoBotonVolver.png"))); // NOI18N
        btnGetBackHome5.setText("PRINCIPAL");
        btnGetBackHome5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGetBackHome5.setContentAreaFilled(false);
        btnGetBackHome5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetBackHome5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnGetBackHome5);
        btnGetBackHome5.setBounds(36, 692, 170, 102);

        btnUpdateClient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdateClient.setText("Actualizar Cliente");
        btnUpdateClient.setContentAreaFilled(false);
        btnUpdateClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateClientActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdateClient);
        btnUpdateClient.setBounds(1050, 760, 160, 23);

        btnRemoveClient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRemoveClient.setText("Eliminar Cliente");
        btnRemoveClient.setContentAreaFilled(false);
        btnRemoveClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveClientActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoveClient);
        btnRemoveClient.setBounds(1300, 760, 150, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLogOutClientCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLogOutClientCCActionPerformed
        if (Validator.isEmpty(txtLogOutClientCC.getText()) && Validator.isEmpty(txtLogOutClientName.getText())
                && Validator.isEmpty(txtLogOutClientLastName.getText()) && Validator.isEmpty(txtLogOutClientPhone.getText())
                && Validator.isEmpty(txtLogOutClientAddress.getText()) && Validator.isEmpty(txtLogOutClientEmail.getText())) {
            JOptionPane.showMessageDialog(this, "Llena todos los campos para registrar el cliente");
            return;
        }
    }//GEN-LAST:event_txtLogOutClientCCActionPerformed

    private void btnRegisterClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterClientActionPerformed
        if (Validator.isEmpty(txtLogOutClientCC.getText()) || Validator.isEmpty(txtLogOutClientName.getText())
                 || Validator.isEmpty(txtLogOutClientLastName.getText()) || Validator.isEmpty(txtLogOutClientPhone.getText())
                || Validator.isEmpty(txtLogOutClientAddress.getText()) || Validator.isEmpty(txtLogOutClientEmail.getText())) {
            JOptionPane.showMessageDialog(this, "Llena todos los campos para registrar el cliente");
            return;
        }

		if (!Validator.lengthBetween(txtLogOutClientCC.getText(), 8, 10) || !Validator.lengthBetween(txtLogOutClientName.getText(), 4, 15)
                || !Validator.lengthBetween(txtLogOutClientLastName.getText(), 4, 20) || !Validator.lengthBetween(txtLogOutClientPhone.getText(), 10, 15)
                || !Validator.lengthBetween(txtLogOutClientAddress.getText(), 10, 200) || !Validator.lengthBetween(txtLogOutClientEmail.getText(), 10, 255)) {
            JOptionPane.showMessageDialog(this, "Verifique la longitud de los datos");
            return;
       	}
        boolean confirm = personController.insertPerson(new Person(txtLogOutClientCC.getText(), txtLogOutClientName.getText(),
                txtLogOutClientLastName.getText(), txtLogOutClientPhone.getText(), txtLogOutClientAddress.getText(), txtLogOutClientEmail.getText()));
        if(confirm){
            System.out.println("se agrego");
        }else{
            System.out.println("No se agrego");
        }
        showTable();
    }//GEN-LAST:event_btnRegisterClientActionPerformed

    private void btnAddSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSeatsActionPerformed
        panelAddSeats.setVisible(true);
        panelAddClients.setVisible(false);
    }//GEN-LAST:event_btnAddSeatsActionPerformed

    private void btnAddClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClientsActionPerformed
        panelAddSeats.setVisible(false);
        panelAddClients.setVisible(true);
    }//GEN-LAST:event_btnAddClientsActionPerformed

    private void btnAddAllSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAllSeatsActionPerformed

        String[] seats = {"A1", "B1", "C1", "D1", "E1", "F1", "G1",
            "A2", "B2", "C2", "D2", "E2", "F2", "G2",
            "A3", "B3", "C3", "D3", "E3", "F3", "G3",
            "A4", "B4", "C4", "D4", "E4", "F4", "G4",
            "A5", "B5", "C5", "D5", "E5", "F5", "G5",
            "A6", "B6", "C6", "D6", "E6", "F6", "G6"
        };

        boolean seatsAdded = seatController.insertAllSeats(seats);

        if (seatsAdded) {
            JOptionPane.showMessageDialog(this, "asientos agregados correctamente a la base de datos");
        } else {
            JOptionPane.showMessageDialog(this, "asientos no agregados");
        }
    }//GEN-LAST:event_btnAddAllSeatsActionPerformed

    private void btnGetBackHome5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetBackHome5ActionPerformed
        FrmCinemaManagement cinema = new FrmCinemaManagement();
        cinema.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGetBackHome5ActionPerformed

    private void btnUpdateClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateClientActionPerformed
        if (Validator.isEmpty(txtLogOutClientCC.getText()) && Validator.isEmpty(txtLogOutClientName.getText())
                && Validator.isEmpty(txtLogOutClientLastName.getText()) && Validator.isEmpty(txtLogOutClientPhone.getText())
                && Validator.isEmpty(txtLogOutClientAddress.getText()) && Validator.isEmpty(txtLogOutClientEmail.getText())) {
            JOptionPane.showMessageDialog(this, "Llena todos los campos para actualizar el cliente");
            return;
        }
        boolean confirm = personController.updatePerson(txtLogOutClientCC.getText(), new Person(txtLogOutClientCC.getText(), txtLogOutClientName.getText(), 
        txtLogOutClientLastName.getText(), txtLogOutClientPhone.getText(), txtLogOutClientAddress.getText(), txtLogOutClientEmail.getText()));
        if(confirm){
            System.out.println("se agrego");
        }else{
            System.out.println("No se agrego");
        }
        showTable();
    }//GEN-LAST:event_btnUpdateClientActionPerformed

    private void btnRemoveClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveClientActionPerformed
        if (Validator.isEmpty(txtLogOutClientCC.getText())) {
            JOptionPane.showMessageDialog(this, "Llena el campo CC para eliminar el cliente");
            return;
        }
        boolean confirm = personController.deletePerson(txtLogOutClientCC.getText());
        if(confirm){
            System.out.println("se agrego");
        }else{
            System.out.println("No se agrego");
        }
        showTable();
    }//GEN-LAST:event_btnRemoveClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogOutClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogOutClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogOutClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogOutClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogOutClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAllSeats;
    private javax.swing.JButton btnAddClients;
    private javax.swing.JButton btnAddSeats;
    private javax.swing.JButton btnGetBackHome5;
    private javax.swing.JButton btnRegisterClient;
    private javax.swing.JButton btnRemoveClient;
    private javax.swing.JButton btnUpdateClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelAddClients;
    private javax.swing.JPanel panelAddSeats;
    private javax.swing.JTable tableClients;
    private javax.swing.JTextField txtLogOutClientAddress;
    private javax.swing.JTextField txtLogOutClientCC;
    private javax.swing.JTextField txtLogOutClientEmail;
    private javax.swing.JTextField txtLogOutClientLastName;
    private javax.swing.JTextField txtLogOutClientName;
    private javax.swing.JTextField txtLogOutClientPhone;
    // End of variables declaration//GEN-END:variables
}
